[project]
name = "trafficfm-arima"
version = "0.1.0"
description = "Environment for ARIMA baseline benchmark"
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.26.0",
    "pandas>=2.0.0",
    "gluonts~=0.15.1",
    "pmdarima>=2.0.0",
    "dotenv>=0.9.9",
    "kaggle==1.7.4.5",
    "salesforce-gift-eval @ git+https://github.com/DensoSVIC/gift-eval.git@traffic",
    "tables>=3.10.1",
]
