_wandb:
    value:
        cli_version: 0.26.0
        e:
            m88tnh3ivev6fo9fi1hajlswp28wpkfz:
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "135087374336"
                        used: "9944563712"
                email: tliao730@usc.edu
                executable: /u/tliao2/TrafficFM/benchmark/fm/moirai/.venv/bin/python3
                git:
                    commit: e5fab52f9a73f3a6739ac5e249261c25ee4fd78e
                    remote: https://github.com/DC-research/TrafficFM.git
                gpu: NVIDIA A40
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-36e74fb7-4f9c-e081-f4a8-58ec436e9409
                host: gpub029.delta.ncsa.illinois.edu
                memory:
                    total: "270174748672"
                os: Linux-5.14.0-427.91.1.el9_4.x86_64-x86_64-with-glibc2.34
                program: -m fm.moirai.chronos_1
                python: CPython 3.10.20
                root: /u/tliao2/TrafficFM/benchmark
                slurm:
                    cluster_name: delta
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "1"
                    gpus_on_node: "1"
                    gpus_per_node: "1"
                    gtids: "0"
                    job_account: bcqc-delta-gpu
                    job_cpus_per_node: "1"
                    job_end_time: "1780400836"
                    job_gid: "202"
                    job_gpus: "2"
                    job_id: "18730336"
                    job_name: chronos_sd2018
                    job_nodelist: gpub029
                    job_num_nodes: "1"
                    job_partition: gpuA40x4
                    job_qos: bcqc-delta-gpu
                    job_start_time: "1780386436"
                    job_uid: "94187"
                    job_user: tliao2
                    jobid: "18730336"
                    localid: "0"
                    mem_per_node: "65536"
                    mpi_type: cray_shasta
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpub029
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /u/tliao2/TrafficFM
                    submit_host: dt-login01.delta.ncsa.illinois.edu
                    task_pid: "124182"
                    tasks_per_node: "1"
                    topology_addr: ss00.ss10.gpub029
                    topology_addr_pattern: switch.switch.node
                startedAt: "2026-06-02T07:47:30.137616Z"
                writerId: m88tnh3ivev6fo9fi1hajlswp28wpkfz
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.20
            "5": 0.26.0
            "6": 4.57.3
            "8":
                - 2
            "12": 0.26.0
            "13": linux-x86_64
batch_size:
    value: 1024
model:
    value: chronos_bolt_base
model_path:
    value: amazon/chronos-bolt-base
num_samples:
    value: 20
