_wandb:
    value:
        cli_version: 0.26.0
        e:
            3yxkqfs3kgdykqxhgas4uxn18ukn8j0e:
                codePath: Finetune/moirai2_finetune.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "135087370240"
                        used: "8473501696"
                email: tliao730@usc.edu
                executable: /u/tliao2/TrafficFM/benchmark/fm/moirai/.venv/bin/python3
                git:
                    commit: 0e5351a8ead0b3c00530296dd6f3c7ba44248fe0
                    remote: https://github.com/DC-research/TrafficFM.git
                gpu: NVIDIA A40
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-00683721-eb6a-65f2-985f-15ac2a5b9de1
                host: gpub055.delta.ncsa.illinois.edu
                memory:
                    total: "270174744576"
                os: Linux-5.14.0-427.91.1.el9_4.x86_64-x86_64-with-glibc2.34
                program: /u/tliao2/TrafficFM/benchmark/../Finetune/moirai2_finetune.py
                python: CPython 3.10.20
                root: .
                slurm:
                    cluster_name: delta
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "1"
                    gpus_on_node: "1"
                    gpus_per_node: "1"
                    gtids: "0"
                    job_account: bcqc-delta-gpu
                    job_cpus_per_node: "1"
                    job_end_time: "1776836787"
                    job_gid: "202"
                    job_gpus: "0"
                    job_id: "17794625"
                    job_name: m2_l1_s358
                    job_nodelist: gpub055
                    job_num_nodes: "1"
                    job_partition: gpuA40x4
                    job_qos: bcqc-delta-gpu
                    job_start_time: "1776822387"
                    job_uid: "94187"
                    job_user: tliao2
                    jobid: "17794625"
                    localid: "0"
                    mem_per_node: "65536"
                    mpi_type: cray_shasta
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpub055
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /u/tliao2/TrafficFM
                    submit_host: dt-login02.delta.ncsa.illinois.edu
                    task_pid: "700234"
                    tasks_per_node: "1"
                    topology_addr: ss00.ss11.gpub055
                    topology_addr_pattern: switch.switch.node
                startedAt: "2026-04-22T01:46:59.037046Z"
                writerId: 3yxkqfs3kgdykqxhgas4uxn18ukn8j0e
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 105
                - 106
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 105
                - 106
            "3":
                - 7
                - 13
                - 16
                - 66
            "4": 3.10.20
            "5": 0.26.0
            "6": 4.57.3
            "8":
                - 2
            "12": 0.26.0
            "13": linux-x86_64
batch_size:
    value: 32
context_length:
    value: 4000
ds_config:
    value: sd_val/2019/short
epochs:
    value: 5
loss:
    value: mae_median
lr:
    value: 1e-05
model:
    value: Moirai2-L1-SD2019-S358
num_batches_per_epoch:
    value: 200
series_limit:
    value: 358
