_wandb:
    value:
        cli_version: 0.26.0
        e:
            xmggzam1n5h18ozn12ub0juc1dta8ibv:
                args:
                    - --term
                    - short
                    - --context_length
                    - "48"
                    - --num_sensors
                    - "0"
                    - --windows_per_sensor
                    - "100"
                    - --bs
                    - "256"
                    - --lrate
                    - "1e-3"
                    - --max_epochs
                    - "50"
                    - --patience
                    - "15"
                    - --wandb_project
                    - TrafficFM
                    - --log_dir
                    - /scratch/bcqc/tliao2/TrafficFM/experiments/mamba_fm/SD/2019/
                codePath: benchmark/fm/mamba/mamba.py
                codePathLocal: fm/mamba/mamba.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "135087370240"
                        used: "8685322240"
                email: angus3938@gmail.com
                executable: /u/tliao2/TrafficFM/benchmark/fm/moirai/.venv/bin/python3
                git:
                    commit: 7c3b46515765313effa09a054610e330d2c55e40
                    remote: https://github.com/DC-research/TrafficFM.git
                gpu: NVIDIA A40
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-a940714d-b7c2-83d9-7b8a-072b5bb51ea3
                host: gpub076.delta.ncsa.illinois.edu
                memory:
                    total: "270174740480"
                os: Linux-5.14.0-427.91.1.el9_4.x86_64-x86_64-with-glibc2.34
                program: /u/tliao2/TrafficFM/benchmark/fm/mamba/mamba.py
                python: CPython 3.10.20
                root: /u/tliao2/TrafficFM/benchmark
                slurm:
                    cluster_name: delta
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "1"
                    gpus_on_node: "1"
                    gpus_per_node: "1"
                    gtids: "0"
                    job_account: bcqc-delta-gpu
                    job_cpus_per_node: "1"
                    job_end_time: "1777371767"
                    job_gid: "202"
                    job_gpus: "3"
                    job_id: "17918022"
                    job_name: mamba_fm
                    job_nodelist: gpub076
                    job_num_nodes: "1"
                    job_partition: gpuA40x4
                    job_qos: bcqc-delta-gpu
                    job_start_time: "1777342967"
                    job_uid: "94187"
                    job_user: tliao2
                    jobid: "17918022"
                    localid: "0"
                    mem_per_node: "32768"
                    mpi_type: cray_shasta
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpub076
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /u/tliao2/TrafficFM
                    submit_host: dt-login02.delta.ncsa.illinois.edu
                    task_pid: "1496606"
                    tasks_per_node: "1"
                    topology_addr: ss00.ss12.gpub076
                    topology_addr_pattern: switch.switch.node
                startedAt: "2026-04-28T02:25:05.282904Z"
                writerId: xmggzam1n5h18ozn12ub0juc1dta8ibv
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 49
                - 51
                - 105
            "2":
                - 1
                - 49
                - 51
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.20
            "5": 0.26.0
            "8":
                - 2
            "12": 0.26.0
            "13": linux-x86_64
bs:
    value: 256
context_length:
    value: 48
d_conv:
    value: 4
d_model:
    value: 64
d_state:
    value: 16
device:
    value: cuda
expand:
    value: 2
log_dir:
    value: /scratch/bcqc/tliao2/TrafficFM/experiments/mamba_fm/SD/2019/
lrate:
    value: 0.001
max_epochs:
    value: 50
num_layers:
    value: 2
num_sensors:
    value: 0
patience:
    value: 15
seed:
    value: 2023
term:
    value: short
wandb_project:
    value: TrafficFM
windows_per_sensor:
    value: 100
