[project]
name = "trafficfm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chronos-forecasting>=2.2.0",
    "dotenv>=0.9.9",
    "kaggle==1.7.4.5",
    "salesforce-gift-eval @ git+https://github.com/DensoSVIC/gift-eval.git@traffic",
    "uni2ts @ git+https://github.com/DensoSVIC/uni2ts.git@traffic",
    "tables>=3.10.1",
    "wandb>=0.26.0",
    "matplotlib>=3.9.4",
]
