_wandb:
    value:
        cli_version: 0.26.1
        e:
            lfvvu4lej3pr3xozwx4oemmh9xr7lg8r:
                args:
                    - --device
                    - cuda
                    - --dataset
                    - SD
                    - --years
                    - "2019"
                    - --model_name
                    - mamba
                    - --max_epochs
                    - "100"
                    - --patience
                    - "30"
                    - --lrate
                    - "1e-3"
                    - --max_train_samples
                    - "5000"
                    - --wandb_project
                    - TrafficFM
                    - --log_dir
                    - /scratch/bcqc/tliao2/TrafficFM/experiments/mamba/SD/2019/
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "135087374336"
                        used: "8535113728"
                email: angus3938@gmail.com
                executable: /u/tliao2/TrafficFM/benchmark/gnn/.venv/bin/python3
                git:
                    commit: 5f44a0ebcda672ffeeb7a58fd8bba7ce8540fcce
                    remote: https://github.com/DC-research/TrafficFM.git
                gpu: NVIDIA A40
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-18606a42-1040-9cc0-efd8-a009490a5d2d
                host: gpub057.delta.ncsa.illinois.edu
                memory:
                    total: "270174752768"
                os: Linux-5.14.0-427.91.1.el9_4.x86_64-x86_64-with-glibc2.34
                program: -m gnn.mamba
                python: CPython 3.10.20
                root: /u/tliao2/TrafficFM/benchmark
                slurm:
                    cluster_name: delta
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "1"
                    gpus_on_node: "1"
                    gpus_per_node: "1"
                    gtids: "0"
                    job_account: bcqc-delta-gpu
                    job_cpus_per_node: "1"
                    job_end_time: "1777285192"
                    job_gid: "202"
                    job_gpus: "3"
                    job_id: "17891756"
                    job_name: mamba_sd
                    job_nodelist: gpub057
                    job_num_nodes: "1"
                    job_partition: gpuA40x4
                    job_qos: bcqc-delta-gpu
                    job_start_time: "1777241992"
                    job_uid: "94187"
                    job_user: tliao2
                    jobid: "17891756"
                    localid: "0"
                    mem_per_node: "32768"
                    mpi_type: cray_shasta
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpub057
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /u/tliao2/TrafficFM
                    submit_host: dt-login04.delta.ncsa.illinois.edu
                    task_pid: "2969281"
                    tasks_per_node: "1"
                    topology_addr: ss00.ss11.gpub057
                    topology_addr_pattern: switch.switch.node
                startedAt: "2026-04-26T22:20:11.149260Z"
                writerId: lfvvu4lej3pr3xozwx4oemmh9xr7lg8r
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.20
            "5": 0.26.1
            "8":
                - 2
            "12": 0.26.1
            "13": linux-x86_64
bs:
    value: 64
clip_grad_value:
    value: 5
d_conv:
    value: 4
d_model:
    value: 64
d_state:
    value: 16
dataset:
    value: SD
device:
    value: cuda
embed_dim:
    value: 10
expand:
    value: 2
horizon:
    value: 12
input_dim:
    value: 3
log_dir:
    value: /scratch/bcqc/tliao2/TrafficFM/experiments/mamba/SD/2019/
lrate:
    value: 0.001
max_epochs:
    value: 100
max_train_samples:
    value: 5000
mode:
    value: train
model_name:
    value: mamba
num_layers:
    value: 2
output_dim:
    value: 1
patience:
    value: 30
pred_horizon:
    value: 0
pred_out_dir:
    value: ""
pretrained_path:
    value: ""
save_predictions:
    value: false
seed:
    value: 2023
seq_len:
    value: 12
test_num_windows:
    value: 0
test_split:
    value: 0
test_stride:
    value: 1
test_stride_mode:
    value: fixed
wandb_project:
    value: TrafficFM
wdecay:
    value: 0
years:
    value: "2019"
